submit50:
  dependencies:
    - beautifulsoup4
    - Mastodon.py
    - openpyxl
  files:
    - !exclude "*"
    - !require test.py
    - !require MastodonOOP.py
    - !require toots.py
check50:
  dependencies:
    - beautifulsoup4
    - Mastodon.py
    - openpyxl
  files:
    - !exclude "*"
    - !require test.py
    - !require MastodonOOP.py
    - !require toots.py
