submit50:
  dependencies:
    - beautifulsoup4
    - Mastodon.py
    - openpyxl
  files:
    - !exclude "*"
    - !require test.py
    - !require MastodonOOP.py
    - !require group_members.txt
check50:
  dependencies:
    - beautifulsoup4
    - Mastodon.py
    - openpyxl
  files:
    - !exclude "*"
    - !require test.py
    - !require MastodonOOP.py
    - !require group_members.txt

